### ISSUE TITLE
PlatformValidationError(osx-arm64)

### ISSUE THREAD

**Issue by BeenLi** [conda-incubator/conda-lock#281]
when I follow the [chipyard tutorial](https://chipyard.readthedocs.io/en/latest/Chipyard-Basics/Initial-Repo-Setup.html#setting-up-the-chipyard-repo) to download conda-lock and type `./build-setup.sh riscv-tools`, it reports the following error:
> raise PlatformValidationError(
conda_lock.errors.PlatformValidationError: Dependencies are not locked for the current platform (osx-arm64)

**Comment by maresb** [comment]
Hi, thanks for the report!

Presumably you are running an M1 or M2 macbook. Because it uses the ARM chipset, many of the dependencies require different packages. When creating the lockfile, chipyard considered only the `linux-64` platform, which corresponds to the AMD chipset. Thus `conda-lock install` doesn't have any way to determine which packages should be installed on your system.

To fix this, chipyard needs to rerun conda-lock with support for both `linux-64` and `osx-arm64` platforms. This can be done by adding a section

```yaml
platforms:
- linux-64
- osx-arm64
```

to the `environment.yml` file, or by using the command-line arguments `--platform=linux-64 --platform=osx-arm64`.

Because the error message isn't so clear, I improved it in #282 so that it would be more explanatory. Hope this helps.
